import { Html, Head, Main, NextScript } from "next/document";
import Navbar from "./parts/Navbar";

export default function Document() {
     return (
          <Html lang="id" className="scroll-smooth">
               <Head>
                    <title>Dolan Pacitan - Portal Wisata Kab. Pacitan</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
               </Head>
               <body>
                    <Navbar />
                    <Main />
                    <NextScript />
               </body>
          </Html>
     );
}
