import Head from "next/head";
import SectionHero from "./sections/Hero";
import SectionAbout from "./sections/About";
import Navbar from "./parts/Navbar";

export default function Home() {
     return (
          <>
               <Head>
                    <title>Dolan Pacitan - Portal Wisata Kab. Pacitan</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
               </Head>
               <div style={{ background: "url('/images/pantai-kasap.jpg')", backgroundSize: "cover", backgroundPosition: "center", backgroundRepeat: "no-repeat", backgroundAttachment: "fixed" }} className="w-screen h-screen overflow-x-hidden">
                    <Navbar />
                    <SectionHero />
                    {/* <SectionAbout /> */}
               </div>
          </>
     );
}
